"""baseline: full Worden Standard v5 schema

Revision ID: f66869dce88e
Revises: 
Create Date: 2026-07-05 18:30:18.270235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66869dce88e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_alerts_metric_name'), 'anomaly_alerts', ['metric_name'], unique=False)
    op.create_index(op.f('ix_anomaly_alerts_tenant_id'), 'anomaly_alerts', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('meta_description', sa.String(length=320), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('read_time_minutes', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_blog_posts_slug')
    )
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=False)
    op.create_table('cashflow_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('threshold_amount', sa.Float(), nullable=False),
    sa.Column('alert_email', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflow_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashflow_entries_week_start'), 'cashflow_entries', ['week_start'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('context', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('license_expiry', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('customer_type', sa.String(length=30), nullable=True),
    sa.Column('is_franchise', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('total_jobs', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('last_job_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('to_email', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('next_service', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trade_key', sa.String(length=50), nullable=False),
    sa.Column('trade_label', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('tonnage', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('binder_cost', sa.Float(), nullable=False),
    sa.Column('final_bid', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('is_large_job', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_type', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=400), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('is_before', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_scan_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('scan_area_sqft', sa.Float(), nullable=True),
    sa.Column('ticket_811', sa.String(length=100), nullable=True),
    sa.Column('ticket_status', sa.String(length=40), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('utilities', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ground_scan_reports_tenant_id'), 'ground_scan_reports', ['tenant_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('urgency', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_label', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('pipeline_stage', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proposal_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_tenant_id'), 'leads', ['tenant_id'], unique=False)
    op.create_table('lien_calendar_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('project_address', sa.String(length=300), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('project_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_furnishing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preliminary_notice_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lien_filing_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('foreclosure_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lien_calendar_entries_lien_filing_deadline'), 'lien_calendar_entries', ['lien_filing_deadline'], unique=False)
    op.create_index(op.f('ix_lien_calendar_entries_state_code'), 'lien_calendar_entries', ['state_code'], unique=False)
    op.create_table('permit_leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('permit_number', sa.String(length=100), nullable=True),
    sa.Column('permit_type', sa.String(length=100), nullable=True),
    sa.Column('permit_status', sa.String(length=50), nullable=True),
    sa.Column('contractor_name', sa.String(length=200), nullable=True),
    sa.Column('contractor_license', sa.String(length=100), nullable=True),
    sa.Column('property_address', sa.String(length=300), nullable=True),
    sa.Column('property_city', sa.String(length=100), nullable=True),
    sa.Column('property_state', sa.String(length=2), nullable=True),
    sa.Column('property_zip', sa.String(length=10), nullable=True),
    sa.Column('project_value', sa.Float(), nullable=True),
    sa.Column('estimated_sqft', sa.Float(), nullable=True),
    sa.Column('permit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('priority_label', sa.String(length=10), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permit_leads_permit_number'), 'permit_leads', ['permit_number'], unique=False)
    op.create_index(op.f('ix_permit_leads_property_state'), 'permit_leads', ['property_state'], unique=False)
    op.create_table('quickbooks_sync',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('local_id', sa.String(length=64), nullable=True),
    sa.Column('qb_id', sa.String(length=100), nullable=True),
    sa.Column('sync_direction', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quickbooks_sync_qb_id'), 'quickbooks_sync', ['qb_id'], unique=False)
    op.create_index(op.f('ix_quickbooks_sync_tenant_id'), 'quickbooks_sync', ['tenant_id'], unique=False)
    op.create_table('safety_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('injured_person', sa.String(length=200), nullable=True),
    sa.Column('body_part_affected', sa.String(length=100), nullable=True),
    sa.Column('days_away', sa.Integer(), nullable=True),
    sa.Column('days_restricted', sa.Integer(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('osha_recordable', sa.Boolean(), nullable=True),
    sa.Column('reported_to_osha', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_toolbox_talks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('presenter', sa.String(length=200), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=True),
    sa.Column('site_address', sa.String(length=300), nullable=True),
    sa.Column('presented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('max_properties', sa.Integer(), nullable=True),
    sa.Column('auto_mail', sa.Boolean(), nullable=True),
    sa.Column('total_properties', sa.Integer(), nullable=True),
    sa.Column('scanned', sa.Integer(), nullable=True),
    sa.Column('mailed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_campaigns_zip_code'), 'scan_campaigns', ['zip_code'], unique=False)
    op.create_table('selectable_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('install_labor_usd', sa.Float(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.Column('available_qty', sa.Float(), nullable=True),
    sa.Column('seasonal_note', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('texture', sa.String(length=60), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight_per_unit', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('model_3d_url', sa.String(length=500), nullable=True),
    sa.Column('datasheet_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selectable_items_category'), 'selectable_items', ['category'], unique=False)
    op.create_index(op.f('ix_selectable_items_sku'), 'selectable_items', ['sku'], unique=True)
    op.create_index(op.f('ix_selectable_items_tenant_id'), 'selectable_items', ['tenant_id'], unique=False)
    op.create_table('subcontractor_roster',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('trade_specialty', sa.String(length=200), nullable=True),
    sa.Column('states_licensed', sa.String(length=300), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_limit', sa.Float(), nullable=True),
    sa.Column('bonded', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=254), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_price_cents', sa.Integer(), nullable=True),
    sa.Column('primary_state', sa.String(length=2), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('custom_domain', sa.String(length=200), nullable=True),
    sa.Column('feature_flags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_tenant_records_slug')
    )
    op.create_index(op.f('ix_tenant_records_slug'), 'tenant_records', ['slug'], unique=False)
    op.create_index(op.f('ix_tenant_records_stripe_customer_id'), 'tenant_records', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_tenant_records_stripe_subscription_id'), 'tenant_records', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_tenant_records_tenant_id'), 'tenant_records', ['tenant_id'], unique=True)
    op.create_table('two_factor_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_two_factor_secrets_username'), 'two_factor_secrets', ['username'], unique=True)
    op.create_table('vdot_bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_number', sa.String(length=50), nullable=True),
    sa.Column('project_name', sa.String(length=400), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('state_route', sa.String(length=50), nullable=True),
    sa.Column('bid_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vdot_bids_bid_date'), 'vdot_bids', ['bid_date'], unique=False)
    op.create_index(op.f('ix_vdot_bids_project_number'), 'vdot_bids', ['project_number'], unique=False)
    op.create_table('workforce_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('osha_card_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('property_address', sa.String(length=300), nullable=True),
    sa.Column('project_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sqft', sa.Float(), nullable=True),
    sa.Column('budget_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_projects_lead_id'), 'catalog_projects', ['lead_id'], unique=False)
    op.create_index(op.f('ix_catalog_projects_tenant_id'), 'catalog_projects', ['tenant_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('client_portal_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_portal_tokens_customer_id'), 'client_portal_tokens', ['customer_id'], unique=False)
    op.create_index(op.f('ix_client_portal_tokens_token_hash'), 'client_portal_tokens', ['token_hash'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('is_large_job', sa.Boolean(), nullable=True),
    sa.Column('lead_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=200), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_lead_id'), 'payment_transactions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), 'payment_transactions', ['stripe_checkout_session_id'], unique=False)
    op.create_table('proposal_outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_title', sa.String(length=300), nullable=False),
    sa.Column('proposal_body', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('lost_reason', sa.String(length=300), nullable=True),
    sa.Column('competitor_won', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposal_outcomes_lead_id'), 'proposal_outcomes', ['lead_id'], unique=False)
    op.create_table('scan_properties',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('parcel_id', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_type', sa.String(length=30), nullable=True),
    sa.Column('land_use_code', sa.String(length=50), nullable=True),
    sa.Column('lot_size_sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['scan_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_properties_campaign_id'), 'scan_properties', ['campaign_id'], unique=False)
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('job_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_customer_id'), 'service_history', ['customer_id'], unique=False)
    op.create_table('subcontractor_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('job_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('schedule_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('would_rehire', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sub_id'], ['subcontractor_roster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcontractor_performance_sub_id'), 'subcontractor_performance', ['sub_id'], unique=False)
    op.create_table('tenant_billing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index(op.f('ix_tenant_billing_events_tenant_id'), 'tenant_billing_events', ['tenant_id'], unique=False)
    op.create_table('catalog_selections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('zone_label', sa.String(length=100), nullable=True),
    sa.Column('override_price_usd', sa.Float(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['selectable_items.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['catalog_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_selections_item_id'), 'catalog_selections', ['item_id'], unique=False)
    op.create_index(op.f('ix_catalog_selections_project_id'), 'catalog_selections', ['project_id'], unique=False)
    op.create_table('gantt_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('task_name', sa.String(length=200), nullable=False),
    sa.Column('phase', sa.String(length=60), nullable=True),
    sa.Column('assigned_to', sa.String(length=200), nullable=True),
    sa.Column('equipment', sa.String(length=200), nullable=True),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('pct_complete', sa.Integer(), nullable=True),
    sa.Column('depends_on', sa.Text(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=True),
    sa.Column('weather_hold', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gantt_tasks_job_id'), 'gantt_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_gantt_tasks_tenant_id'), 'gantt_tasks', ['tenant_id'], unique=False)
    op.create_table('plan_markups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('catalog_project_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('zones', sa.Text(), nullable=True),
    sa.Column('total_area_sqft', sa.Float(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['catalog_project_id'], ['catalog_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_markups_catalog_project_id'), 'plan_markups', ['catalog_project_id'], unique=False)
    op.create_index(op.f('ix_plan_markups_tenant_id'), 'plan_markups', ['tenant_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('roof_condition', sa.String(length=10), nullable=True),
    sa.Column('driveway_condition', sa.String(length=10), nullable=True),
    sa.Column('drainage_condition', sa.String(length=10), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('condition_narrative', sa.Text(), nullable=True),
    sa.Column('services_recommended', sa.Text(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('estimated_sqft', sa.Float(), nullable=True),
    sa.Column('estimate_low', sa.Float(), nullable=True),
    sa.Column('estimate_high', sa.Float(), nullable=True),
    sa.Column('mailer_html', sa.Text(), nullable=True),
    sa.Column('lob_letter_id', sa.String(length=100), nullable=True),
    sa.Column('lob_status', sa.String(length=50), nullable=True),
    sa.Column('mailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['scan_properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_results_property_id'), 'scan_results', ['property_id'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('lead_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('crew_assigned', sa.String(length=300), nullable=True),
    sa.Column('equipment_assigned', sa.String(length=300), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_job_id'), 'work_orders', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_job_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_scan_results_property_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_plan_markups_tenant_id'), table_name='plan_markups')
    op.drop_index(op.f('ix_plan_markups_catalog_project_id'), table_name='plan_markups')
    op.drop_table('plan_markups')
    op.drop_index(op.f('ix_gantt_tasks_tenant_id'), table_name='gantt_tasks')
    op.drop_index(op.f('ix_gantt_tasks_job_id'), table_name='gantt_tasks')
    op.drop_table('gantt_tasks')
    op.drop_index(op.f('ix_catalog_selections_project_id'), table_name='catalog_selections')
    op.drop_index(op.f('ix_catalog_selections_item_id'), table_name='catalog_selections')
    op.drop_table('catalog_selections')
    op.drop_index(op.f('ix_tenant_billing_events_tenant_id'), table_name='tenant_billing_events')
    op.drop_table('tenant_billing_events')
    op.drop_index(op.f('ix_subcontractor_performance_sub_id'), table_name='subcontractor_performance')
    op.drop_table('subcontractor_performance')
    op.drop_index(op.f('ix_service_history_customer_id'), table_name='service_history')
    op.drop_table('service_history')
    op.drop_index(op.f('ix_scan_properties_campaign_id'), table_name='scan_properties')
    op.drop_table('scan_properties')
    op.drop_index(op.f('ix_proposal_outcomes_lead_id'), table_name='proposal_outcomes')
    op.drop_table('proposal_outcomes')
    op.drop_index(op.f('ix_payment_transactions_stripe_checkout_session_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_lead_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_client_portal_tokens_token_hash'), table_name='client_portal_tokens')
    op.drop_index(op.f('ix_client_portal_tokens_customer_id'), table_name='client_portal_tokens')
    op.drop_table('client_portal_tokens')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_catalog_projects_tenant_id'), table_name='catalog_projects')
    op.drop_index(op.f('ix_catalog_projects_lead_id'), table_name='catalog_projects')
    op.drop_table('catalog_projects')
    op.drop_table('workforce_members')
    op.drop_index(op.f('ix_vdot_bids_project_number'), table_name='vdot_bids')
    op.drop_index(op.f('ix_vdot_bids_bid_date'), table_name='vdot_bids')
    op.drop_table('vdot_bids')
    op.drop_index(op.f('ix_two_factor_secrets_username'), table_name='two_factor_secrets')
    op.drop_table('two_factor_secrets')
    op.drop_index(op.f('ix_tenant_records_tenant_id'), table_name='tenant_records')
    op.drop_index(op.f('ix_tenant_records_stripe_subscription_id'), table_name='tenant_records')
    op.drop_index(op.f('ix_tenant_records_stripe_customer_id'), table_name='tenant_records')
    op.drop_index(op.f('ix_tenant_records_slug'), table_name='tenant_records')
    op.drop_table('tenant_records')
    op.drop_table('subcontractor_roster')
    op.drop_index(op.f('ix_selectable_items_tenant_id'), table_name='selectable_items')
    op.drop_index(op.f('ix_selectable_items_sku'), table_name='selectable_items')
    op.drop_index(op.f('ix_selectable_items_category'), table_name='selectable_items')
    op.drop_table('selectable_items')
    op.drop_index(op.f('ix_scan_campaigns_zip_code'), table_name='scan_campaigns')
    op.drop_table('scan_campaigns')
    op.drop_table('safety_toolbox_talks')
    op.drop_table('safety_incidents')
    op.drop_index(op.f('ix_quickbooks_sync_tenant_id'), table_name='quickbooks_sync')
    op.drop_index(op.f('ix_quickbooks_sync_qb_id'), table_name='quickbooks_sync')
    op.drop_table('quickbooks_sync')
    op.drop_index(op.f('ix_permit_leads_property_state'), table_name='permit_leads')
    op.drop_index(op.f('ix_permit_leads_permit_number'), table_name='permit_leads')
    op.drop_table('permit_leads')
    op.drop_index(op.f('ix_lien_calendar_entries_state_code'), table_name='lien_calendar_entries')
    op.drop_index(op.f('ix_lien_calendar_entries_lien_filing_deadline'), table_name='lien_calendar_entries')
    op.drop_table('lien_calendar_entries')
    op.drop_index(op.f('ix_leads_tenant_id'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_ground_scan_reports_tenant_id'), table_name='ground_scan_reports')
    op.drop_table('ground_scan_reports')
    op.drop_table('gallery_images')
    op.drop_table('estimates')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('crew')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_cashflow_entries_week_start'), table_name='cashflow_entries')
    op.drop_table('cashflow_entries')
    op.drop_table('cashflow_alerts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_anomaly_alerts_tenant_id'), table_name='anomaly_alerts')
    op.drop_index(op.f('ix_anomaly_alerts_metric_name'), table_name='anomaly_alerts')
    op.drop_table('anomaly_alerts')
    # ### end Alembic commands ###
