"""
legal_tables.py — GENERATED. Do not hand-edit.

Written by scripts/build-python-legal-tables.mjs from the cited datasets in
src/data/legal/. Every row here has a statute citation and a verification date
because the source rows do; nothing was added that the source did not state.

Regenerate with:
    node scripts/build-python-legal-tables.mjs

WHY IT IS GENERATED RATHER THAN MAINTAINED
──────────────────────────────────────────
The Python side used to keep its own copies — 13 states in the lien calculator,
3 in the compliance ability — and they drifted from the JavaScript tables the
advisory pages serve. A second hand-maintained copy of fifty-one jurisdictions
of statute law does not stay in step, and the way you find out is a missed
filing deadline.

WHAT A NULL MEANS HERE
──────────────────────
The source did not state it. It does not mean zero, and it does not mean the
requirement is absent. Callers must decline to compute rather than substitute a
default — a plausible date carries the same authority as a correct one and is
indistinguishable to the person relying on it.
"""

# ruff: noqa: E501

JURISDICTION_COUNT = 51

LIEN_LAWS: dict[str, dict] = {
    "AL": {"state": "Alabama", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days (4 months) from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Ala. Code § 35-11-210 et seq.", "notes": "Homestead exemptions may limit lien rights on owner-occupied residential property.", "last_verified": "2026-01-01"},
    "AK": {"state": "Alaska", "lien_filing_days": 120, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from completion of construction; 15-day written notice of lien rights required for subcontractors before first furnishing", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 5, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Before or within 5 days after first furnishing", "notice_of_intent_days": 10, "citation": "AS § 34.35.050 et seq.", "notes": "Notice of right to lien required within 5 days of first furnishing. 10-day notice of intent to lien required before filing.", "last_verified": "2026-01-01"},
    "AZ": {"state": "Arizona", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from completion, abandonment, or last furnishing of materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 20, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 20 days of first furnishing", "notice_of_intent_days": None, "citation": "A.R.S. § 33-981 et seq.", "notes": "Preliminary 20-day notice required for all parties except GC with direct contract with owner. Residential properties have same rules.", "last_verified": "2026-01-01"},
    "AR": {"state": "Arkansas", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 15, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 10, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 10 days of first furnishing for suppliers", "notice_of_intent_days": None, "citation": "Ark. Code Ann. § 18-44-101 et seq.", "notes": "Foreclosure suit must be filed within 15 months of last furnishing. Residential property has special notice requirements.", "last_verified": "2026-01-01"},
    "CA": {"state": "California", "lien_filing_days": 90, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from completion of the project (notice of completion triggers 30-day filing period for GCs, 60 days for subs/suppliers)", "lien_filing_rule": None, "foreclosure_days": 90, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 20, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 20 days of first furnishing", "notice_of_intent_days": None, "citation": "Cal. Civ. Code § 8100 et seq.", "notes": "Preliminary 20-day notice required for all claimants except direct contractors. If owner records Notice of Completion: GC has 60 days, subs/suppliers have 30 days. Joint check protections available. Most robust lien law in the US.", "last_verified": "2026-01-01"},
    "CO": {"state": "Colorado", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last date of furnishing labor or materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Colo. Rev. Stat. § 38-22-101 et seq.", "notes": "No preliminary notice required. Lien statement must be filed within 4 months. Must commence foreclosure within 6 months of last furnishing or date lien filed.", "last_verified": "2026-01-01"},
    "CT": {"state": "Connecticut", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last day of furnishing services or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Conn. Gen. Stat. § 49-33 et seq.", "notes": "Certificate of lien must be filed within 90 days. No preliminary notice required. Must serve copy of certificate on property owner within 30 days of filing.", "last_verified": "2026-01-01"},
    "DE": {"state": "Delaware", "lien_filing_days": 120, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "Within 120 days of last work: 60 days for original contractors; 90 days for subcontractors and suppliers from notice of completion", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Del. Code Ann. tit. 25, § 2701 et seq.", "notes": "Suit must commence within 1 year of lien filing. Statement of lien filed with Prothonotary.", "last_verified": "2026-01-01"},
    "DC": {"state": "District of Columbia", "lien_filing_days": 90, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "Ninety days after the earlier of completion or termination of the project; may be recorded during construction", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "D.C. Code § 40-301.01 et seq. (filing deadline at § 40-301.02)", "notes": "Public property is generally not lienable; verify notice and filing prerequisites against current District statute before action.", "last_verified": "2026-01-01"},
    "FL": {"state": "Florida", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials on the project", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 45, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Before first furnishing or within 45 days of first furnishing", "notice_of_intent_days": None, "citation": "Fla. Stat. § 713.001 et seq.", "notes": "Notice to Owner (NTO) required for all lienors except direct contractors. NTO must be served before first furnishing or within 45 days. Claim of lien must be filed within 90 days of last furnishing. Foreclose within 1 year of recording.", "last_verified": "2026-01-01"},
    "GA": {"state": "Georgia", "lien_filing_days": 90, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "Within 90 days of completion of the contract or last work performed", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 30 days of first furnishing", "notice_of_intent_days": 30, "citation": "O.C.G.A. § 44-14-360 et seq.", "notes": "Preliminary notice (Notice to Contractor) required for subs within 30 days of first furnishing. Claim of lien must be filed within 90 days of completion. Must commence foreclosure within 365 days of lien filing.", "last_verified": "2026-01-01"},
    "HI": {"state": "Hawaii", "lien_filing_days": 45, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "45 days from completion or abandonment of the improvement", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 10, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Before or within 10 days of first furnishing", "notice_of_intent_days": None, "citation": "Haw. Rev. Stat. § 507-41 et seq.", "notes": "Notice of lien rights required within 10 days for subcontractors. Claim of lien filed within 45 days. Must commence suit within 1 year of last furnishing.", "last_verified": "2026-01-01"},
    "ID": {"state": "Idaho", "lien_filing_days": 90, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from completion or cessation of labor", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 5, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 5 days of first furnishing for some claimants", "notice_of_intent_days": None, "citation": "Idaho Code § 45-501 et seq.", "notes": "Claim of lien filed within 90 days of completion. Suit must be commenced within 6 months of filing. Residential property: notice to owner required.", "last_verified": "2026-01-01"},
    "IL": {"state": "Illinois", "lien_filing_days": None, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "Four months after completion, or four months after completion of any extra or additional work", "lien_filing_rule": {"kind": "calendar_months", "months_after": 4, "day_of_month": None, "residential_months_after": None, "anchor": "completion"}, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "770 ILCS 60/1 et seq. (Illinois Mechanics Lien Act)", "notes": "Subcontractors must send 90-day notice to owner to preserve lien rights. Two-year foreclosure period. Owner-occupied residential under $10,000 exempt.", "last_verified": "2026-01-01"},
    "IN": {"state": "Indiana", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from completion of work or last furnishing", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 60, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 60 days of first furnishing for subs/suppliers to give notice to owner", "notice_of_intent_days": None, "citation": "Ind. Code § 32-28-3-1 et seq.", "notes": "Prior notice not required to file lien but sub-contractors must notify owner within 60 days of first furnishing to preserve rights against owner. Lien statement filed within 90 days of last work.", "last_verified": "2026-01-01"},
    "IA": {"state": "Iowa", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last date of furnishing labor or materials", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 30 days of first furnishing", "notice_of_intent_days": None, "citation": "Iowa Code § 572.1 et seq.", "notes": "Subcontractors must serve preliminary notice on owner within 30 days of first furnishing. Lien statement filed within 90 days. Foreclosure within 2 years.", "last_verified": "2026-01-01"},
    "KS": {"state": "Kansas", "lien_filing_days": None, "lien_filing_anchor": None, "lien_filing_also_capped_by": None, "lien_filing_note": "Four months after material was last furnished or labor last performed under the contract", "lien_filing_rule": {"kind": "calendar_months", "months_after": 4, "day_of_month": None, "residential_months_after": None, "anchor": "last_furnishing"}, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": None, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 3 months of first furnishing for suppliers", "notice_of_intent_days": None, "citation": "Kan. Stat. Ann. § 60-1101 et seq.", "notes": "Material suppliers must give notice of furnishing within 3 months. Lien statement filed within 4 months of completion. Foreclosure within 1 year of lien filing.", "last_verified": "2026-01-01"},
    "KY": {"state": "Kentucky", "lien_filing_days": 180, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "6 months from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": None, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Ky. Rev. Stat. § 376.010 et seq.", "notes": "No preliminary notice required. Statement of lien must be filed within 6 months. Foreclosure suit must be filed within 1 year of the debt becoming due.", "last_verified": "2026-01-01"},
    "LA": {"state": "Louisiana", "lien_filing_days": 60, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "60 days from filing of Notice of Termination of Work or substantial completion", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": None, "preliminary_notice_note": "Notice of contract must be filed within 30 days of contract execution", "notice_of_intent_days": None, "citation": "La. Rev. Stat. § 9:4801 et seq. (Louisiana Private Works Act)", "notes": "Owner must file Notice of Termination to trigger 60-day period; without this, claimants have up to 1 year from last work. Statement of claim filed in mortgage records.", "last_verified": "2026-01-01"},
    "ME": {"state": "Maine", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Me. Rev. Stat. tit. 10, § 3251 et seq.", "notes": "No preliminary notice required. Attested statement of lien must be filed within 90 days. Foreclose within 1 year of last furnishing.", "last_verified": "2026-01-01"},
    "MD": {"state": "Maryland", "lien_filing_days": 180, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "Within 180 days of last day of furnishing labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 120, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 120 days of first furnishing for subcontractors", "notice_of_intent_days": None, "citation": "Md. Code Ann., Real Prop. § 9-101 et seq.", "notes": "Preliminary notice required from subcontractors and material suppliers within 120 days of first furnishing. Petition for mechanics lien filed in circuit court within 180 days.", "last_verified": "2026-01-01"},
    "MA": {"state": "Massachusetts", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last date of furnishing labor or materials", "lien_filing_rule": None, "foreclosure_days": 90, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 30 days of first furnishing for subcontractors and suppliers", "notice_of_intent_days": None, "citation": "M.G.L. c. 254, § 1 et seq.", "notes": "Subcontractors must give notice to owner within 30 days of first furnishing to preserve lien rights. Statement of lien recorded within 90 days. Commence enforcement within 90 days of recording.", "last_verified": "2026-01-01"},
    "MI": {"state": "Michigan", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last day of furnishing labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 20, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 20 days of first furnishing", "notice_of_intent_days": None, "citation": "MCL § 570.1101 et seq. (Construction Lien Act)", "notes": "Notice of furnishing required within 20 days for subcontractors and suppliers to preserve lien rights. Claim of lien recorded within 90 days. Residential lien fund available for homeowners.", "last_verified": "2026-01-01"},
    "MN": {"state": "Minnesota", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 45, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 45 days of first furnishing", "notice_of_intent_days": None, "citation": "Minn. Stat. § 514.01 et seq.", "notes": "Pre-lien notice required within 45 days of first furnishing for subcontractors. Lien statement filed within 120 days. Foreclosure commenced within 1 year.", "last_verified": "2026-01-01"},
    "MS": {"state": "Mississippi", "lien_filing_days": 365, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "1 year from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Miss. Code Ann. § 85-7-131 et seq.", "notes": "Mississippi has a relatively long 1-year filing period. No preliminary notice required. Enforcement suit within 1 year of lien filing. Residential homestead exemptions apply.", "last_verified": "2026-01-01"},
    "MO": {"state": "Missouri", "lien_filing_days": None, "lien_filing_anchor": "indebtedness_accrued", "lien_filing_also_capped_by": None, "lien_filing_note": "Six months after the indebtedness accrued (60 days for rental equipment, from its last removal)", "lien_filing_rule": {"kind": "calendar_months", "months_after": 6, "day_of_month": None, "residential_months_after": None, "anchor": "indebtedness_accrued"}, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 10, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 10 days of first delivery for suppliers to owners", "notice_of_intent_days": None, "citation": "Mo. Rev. Stat. § 429.010 et seq.", "notes": "Material suppliers must give written notice to owner within 10 days of first delivery. Just and true account filed within 6 months. Suit commenced within 1 year.", "last_verified": "2026-01-01"},
    "MT": {"state": "Montana", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 20, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 20 days of first furnishing", "notice_of_intent_days": None, "citation": "Mont. Code Ann. § 71-3-521 et seq.", "notes": "Notice of right to lien must be served on owner within 20 days of first furnishing. Claim filed within 90 days. Suit commenced within 2 years.", "last_verified": "2026-01-01"},
    "NE": {"state": "Nebraska", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 10, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 10 days of first furnishing for suppliers", "notice_of_intent_days": None, "citation": "Neb. Rev. Stat. § 52-125 et seq.", "notes": "Material suppliers must give notice within 10 days. Lien filed within 120 days. Foreclosure within 2 years.", "last_verified": "2026-01-01"},
    "NV": {"state": "Nevada", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing or from date work stopped", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 31, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 31 days of first furnishing", "notice_of_intent_days": None, "citation": "NRS § 108.221 et seq.", "notes": "Preliminary notice (Notice of Right to Lien) required within 31 days of first furnishing for subs/suppliers. Notice of lien must be filed within 90 days. Suit within 6 months.", "last_verified": "2026-01-01"},
    "NH": {"state": "New Hampshire", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days (4 months) from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "RSA 447:1 et seq.", "notes": "No preliminary notice required. Claim must be filed within 120 days. Suit within 1 year.", "last_verified": "2026-01-01"},
    "NJ": {"state": "New Jersey", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last date of providing labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "N.J. Stat. Ann. § 2A:44A-1 et seq. (New Jersey Construction Lien Law)", "notes": "No preliminary notice required. Lien claim filed within 90 days of last furnishing. Copy served on owner within 30 days of filing. Suit within 1 year of filing.", "last_verified": "2026-01-01"},
    "NM": {"state": "New Mexico", "lien_filing_days": 120, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from the date that substantial completion occurs or work is abandoned", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 60, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 60 days of first furnishing", "notice_of_intent_days": None, "citation": "N.M. Stat. Ann. § 48-2-1 et seq.", "notes": "Notice of right to lien required from subcontractors within 60 days. Claim of lien filed within 120 days. Suit within 2 years.", "last_verified": "2026-01-01"},
    "NY": {"state": "New York", "lien_filing_days": 240, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "8 months from last furnishing on private projects; 30 days on public projects from final payment date", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "NY Lien Law § 3 et seq.", "notes": "Notice of lien filed with county clerk within 8 months on private projects. Must be verified. Foreclose or extend within 1 year of filing. Public works use Mechanic's Lien Law Art. 2.", "last_verified": "2026-01-01"},
    "NC": {"state": "North Carolina", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 15, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 15 days of first furnishing for subs/suppliers", "notice_of_intent_days": None, "citation": "N.C. Gen. Stat. § 44A-7 et seq.", "notes": "Notice to lien agent required for projects over $30,000. Subs must serve notice within 15 days of first furnishing. Claim of lien on real property filed within 120 days. Commence action within 180 days of filing.", "last_verified": "2026-01-01"},
    "ND": {"state": "North Dakota", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 1095, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "N.D. Cent. Code § 35-27-01 et seq.", "notes": "No preliminary notice required. Verified statement of lien filed within 90 days. Suit within 3 years of filing.", "last_verified": "2026-01-01"},
    "OH": {"state": "Ohio", "lien_filing_days": 75, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "75 days from last furnishing of labor or materials; 60 days from original contractor's last work", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 21, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 21 days of first furnishing for subcontractors", "notice_of_intent_days": None, "citation": "Ohio Rev. Code § 1311.01 et seq.", "notes": "Subcontractors must serve Notice of Furnishing within 21 days of first furnishing. Affidavit of mechanics lien filed within 75 days. Suit within 6 years of filing.", "last_verified": "2026-01-01"},
    "OK": {"state": "Oklahoma", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from completion of work or last furnishing", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 75, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 75 days of first furnishing", "notice_of_intent_days": None, "citation": "Okla. Stat. Ann. tit. 42, § 141 et seq.", "notes": "Written notice to owner by subs required within 75 days of first furnishing. Claim filed within 90 days of last work. Suit within 1 year.", "last_verified": "2026-01-01"},
    "OR": {"state": "Oregon", "lien_filing_days": 75, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "75 days from completion of construction for subcontractors; 120 days for original contractors", "lien_filing_rule": None, "foreclosure_days": 120, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 8, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 8 days of first furnishing", "notice_of_intent_days": None, "citation": "ORS § 87.001 et seq.", "notes": "Notice of right to lien must be served on owner within 8 days of first furnishing for subs/suppliers. Claim of lien filed within 75 days (subs) or 120 days (GC). Enforcement within 120 days of filing.", "last_verified": "2026-01-01"},
    "PA": {"state": "Pennsylvania", "lien_filing_days": 180, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "6 months from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 30 days of first furnishing for subs", "notice_of_intent_days": None, "citation": "49 Pa. Stat. Ann. § 1101 et seq. (Pennsylvania Mechanics' Lien Law)", "notes": "Subcontractors must file a preliminary notice with the prothonotary within 30 days of first furnishing. Claim of lien filed within 6 months. Suit within 2 years.", "last_verified": "2026-01-01"},
    "RI": {"state": "Rhode Island", "lien_filing_days": 200, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "200 days from last furnishing of labor or materials; if completion posted, 100 days from posting", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "R.I. Gen. Laws § 34-28-1 et seq.", "notes": "No preliminary notice required. Notice of intention to claim lien filed within 200 days. Suit within 1 year of filing.", "last_verified": "2026-01-01"},
    "SC": {"state": "South Carolina", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "last_furnishing", "preliminary_notice_required": True, "preliminary_notice_days": 30, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 30 days of first furnishing for subs", "notice_of_intent_days": None, "citation": "S.C. Code Ann. § 29-5-10 et seq.", "notes": "Subcontractors must serve notice within 30 days of first furnishing. Mechanic's lien filed within 90 days. Enforcement within 1 year.", "last_verified": "2026-01-01"},
    "SD": {"state": "South Dakota", "lien_filing_days": 120, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "120 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 2190, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "S.D. Codified Laws § 44-9-1 et seq.", "notes": "No preliminary notice required. Statement of lien filed within 120 days. Suit within 6 years.", "last_verified": "2026-01-01"},
    "TN": {"state": "Tennessee", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 90, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 90 days of first furnishing (remote contractors notice to prime)", "notice_of_intent_days": 10, "citation": "Tenn. Code Ann. § 66-11-101 et seq.", "notes": "Notice of nonpayment required from remote contractors. Lien notice filed within 90 days. 10-day notice of intent to lien required. Suit within 1 year.", "last_verified": "2026-01-01"},
    "TX": {"state": "Texas", "lien_filing_days": 15, "lien_filing_anchor": "completion", "lien_filing_also_capped_by": None, "lien_filing_note": "Affidavit filed by 15th day of 4th calendar month after day work completed (residential: 3rd month); constitutional lien attaches automatically", "lien_filing_rule": {"kind": "calendar_month_day", "day_of_month": 15, "months_after": 4, "residential_months_after": 3, "anchor": "completion"}, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": "Monthly notice by 15th of 2nd month following furnishing", "notice_of_intent_days": None, "citation": "Tex. Prop. Code Ch. 53", "notes": "Texas has dual lien system: constitutional (auto-attaches) and statutory. Statutory lien requires monthly notices by 15th of 2nd month following furnishing for each unpaid month. Residential projects have different rules under Ch. 53. Deadline calculated from last work month. Highly technical - errors forfeit rights.", "last_verified": "2026-01-01"},
    "UT": {"state": "Utah", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from completion of the original contract or last furnishing", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 20, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 20 days of first furnishing", "notice_of_intent_days": None, "citation": "Utah Code Ann. § 38-1a-101 et seq.", "notes": "Preliminary notice required within 20 days of first furnishing for all lienors except direct contractors. Lien filed within 90 days of completion. Suit within 12 months.", "last_verified": "2026-01-01"},
    "VT": {"state": "Vermont", "lien_filing_days": 180, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "180 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "9 V.S.A. § 1921 et seq.", "notes": "No preliminary notice required. Statement of lien recorded within 180 days. Suit within 1 year.", "last_verified": "2026-01-01"},
    "VA": {"state": "Virginia", "lien_filing_days": 90, "lien_filing_anchor": "month_end_of_last_furnishing", "lien_filing_also_capped_by": {"days": 90, "from": "completion"}, "lien_filing_note": "90 days from the last day of the month in which labor or materials were last furnished, and in no event later than 90 days from completion — whichever comes first", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 150, "preliminary_notice_anchor": "last_furnishing", "preliminary_notice_note": "Within 150 days of last furnishing", "notice_of_intent_days": None, "citation": "Va. Code Ann. § 43-1 et seq.", "notes": "Subcontractors must give notice to owner of intent to file lien within 150 days of last furnishing. Memorandum of mechanic's lien filed within 90 days. Action to enforce within 6 months.", "last_verified": "2026-01-01"},
    "WA": {"state": "Washington", "lien_filing_days": 90, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "90 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 240, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 60, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 60 days of first furnishing", "notice_of_intent_days": None, "citation": "RCW § 60.04.011 et seq.", "notes": "Notice to owner/prime required within 60 days of first furnishing for subs/suppliers. Claim of lien filed within 90 days. Suit within 8 months.", "last_verified": "2026-01-01"},
    "WV": {"state": "West Virginia", "lien_filing_days": 100, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "100 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 365, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "W. Va. Code § 38-2-1 et seq.", "notes": "No preliminary notice required. Verified notice of lien filed within 100 days. Suit within 1 year.", "last_verified": "2026-01-01"},
    "WI": {"state": "Wisconsin", "lien_filing_days": 180, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "6 months from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 730, "foreclosure_from": "filing", "preliminary_notice_required": True, "preliminary_notice_days": 60, "preliminary_notice_anchor": "first_furnishing", "preliminary_notice_note": "Within 60 days of first furnishing for subs/suppliers", "notice_of_intent_days": None, "citation": "Wis. Stat. § 779.01 et seq.", "notes": "Subcontractors and suppliers must serve owner/prime with notice within 60 days of first furnishing. Claim for lien filed within 6 months. Suit within 2 years.", "last_verified": "2026-01-01"},
    "WY": {"state": "Wyoming", "lien_filing_days": 150, "lien_filing_anchor": "last_furnishing", "lien_filing_also_capped_by": None, "lien_filing_note": "150 days from last furnishing of labor or materials", "lien_filing_rule": None, "foreclosure_days": 180, "foreclosure_from": "filing", "preliminary_notice_required": False, "preliminary_notice_days": None, "preliminary_notice_anchor": None, "preliminary_notice_note": None, "notice_of_intent_days": None, "citation": "Wyo. Stat. Ann. § 29-1-101 et seq.", "notes": "No preliminary notice required. Lien filed within 150 days. Suit within 180 days of lien filing.", "last_verified": "2026-01-01"},
}

PREVAILING_WAGE: dict[str, dict] = {
    "AL": {"state": "Alabama", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Ala. Code § 39-5-1", "last_verified": "2026-01-01"},
    "AK": {"state": "Alaska", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "AS § 36.05.010 et seq.", "last_verified": "2026-01-01"},
    "AZ": {"state": "Arizona", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "A.R.S. § 34-323 (highway projects only)", "last_verified": "2026-01-01"},
    "AR": {"state": "Arkansas", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Ark. Code Ann. § 22-9-301 et seq. (highway projects)", "last_verified": "2026-01-01"},
    "CA": {"state": "California", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "California DIR - Division of Labor Standards Enforcement (DLSE)", "threshold_public_works_usd": 1000, "davis_bacon_applies": True, "citation": "Cal. Lab. Code § 1720 et seq.", "last_verified": "2026-01-01"},
    "CO": {"state": "Colorado", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Colorado Department of Labor and Employment (CDLE)", "threshold_public_works_usd": 500000, "davis_bacon_applies": True, "citation": "C.R.S. § 8-17-101 et seq.", "last_verified": "2026-01-01"},
    "CT": {"state": "Connecticut", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Connecticut Department of Labor", "threshold_public_works_usd": 100000, "davis_bacon_applies": True, "citation": "CGS § 31-53 et seq.", "last_verified": "2026-01-01"},
    "DE": {"state": "Delaware", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Delaware Department of Labor", "threshold_public_works_usd": 500000, "davis_bacon_applies": True, "citation": "29 Del. Code § 6960 et seq.", "last_verified": "2026-01-01"},
    "DC": {"state": "District of Columbia", "prevailing_wage_law": True, "law_scope": "District public construction contracts", "administered_by": "District Department of Employment Services (DOES)", "threshold_public_works_usd": 200000, "davis_bacon_applies": True, "citation": "District public works prevailing wage requirements and related procurement rules", "last_verified": "2026-01-01"},
    "FL": {"state": "Florida", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Fla. Stat. § 215.19 (repealed; no current PW law)", "last_verified": "2026-01-01"},
    "GA": {"state": "Georgia", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "O.C.G.A. § 13-10-80 et seq. (preempted for local)", "last_verified": "2026-01-01"},
    "HI": {"state": "Hawaii", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Hawaii Department of Labor and Industrial Relations (DLIR)", "threshold_public_works_usd": 2000, "davis_bacon_applies": True, "citation": "HRS § 104-1 et seq.", "last_verified": "2026-01-01"},
    "ID": {"state": "Idaho", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Idaho Code § 44-1001 et seq. (limited to highway projects)", "last_verified": "2026-01-01"},
    "IL": {"state": "Illinois", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Illinois Department of Labor", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "820 ILCS 130/1 et seq.", "last_verified": "2026-01-01"},
    "IN": {"state": "Indiana", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "IC 5-16-7 (repealed 2015)", "last_verified": "2026-01-01"},
    "IA": {"state": "Iowa", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Iowa Code § 91C.1 (limited)", "last_verified": "2026-01-01"},
    "KS": {"state": "Kansas", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "K.S.A. 44-201 (limited)", "last_verified": "2026-01-01"},
    "KY": {"state": "Kentucky", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Kentucky Labor Cabinet", "threshold_public_works_usd": 250000, "davis_bacon_applies": True, "citation": "KRS 337.010 et seq.", "last_verified": "2026-01-01"},
    "LA": {"state": "Louisiana", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "La. Rev. Stat. § 38:2241 (limited)", "last_verified": "2026-01-01"},
    "ME": {"state": "Maine", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Maine Department of Labor", "threshold_public_works_usd": 50000, "davis_bacon_applies": True, "citation": "26 M.R.S.A. § 1301 et seq.", "last_verified": "2026-01-01"},
    "MD": {"state": "Maryland", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Maryland Commissioner of Labor and Industry", "threshold_public_works_usd": 500000, "davis_bacon_applies": True, "citation": "Md. Code Ann., State Fin. & Proc. § 17-201 et seq.", "last_verified": "2026-01-01"},
    "MA": {"state": "Massachusetts", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Massachusetts Department of Labor Standards", "threshold_public_works_usd": 10000, "davis_bacon_applies": True, "citation": "M.G.L. c. 149, § 26 et seq.", "last_verified": "2026-01-01"},
    "MI": {"state": "Michigan", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Michigan Department of Labor and Economic Opportunity (LEO)", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "MCL § 408.551 et seq.", "last_verified": "2026-01-01"},
    "MN": {"state": "Minnesota", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Minnesota Department of Labor and Industry (DLI)", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "Minn. Stat. § 177.41 et seq.", "last_verified": "2026-01-01"},
    "MS": {"state": "Mississippi", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Miss. Code Ann. § 31-5-1 (no current PW law)", "last_verified": "2026-01-01"},
    "MO": {"state": "Missouri", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Missouri Department of Labor and Industrial Relations", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "Mo. Rev. Stat. § 290.210 et seq.", "last_verified": "2026-01-01"},
    "MT": {"state": "Montana", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Montana Department of Labor and Industry", "threshold_public_works_usd": 25000, "davis_bacon_applies": True, "citation": "Mont. Code Ann. § 18-2-401 et seq.", "last_verified": "2026-01-01"},
    "NE": {"state": "Nebraska", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Neb. Rev. Stat. § 73-101 et seq. (limited)", "last_verified": "2026-01-01"},
    "NV": {"state": "Nevada", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Nevada Office of the Labor Commissioner", "threshold_public_works_usd": 100000, "davis_bacon_applies": True, "citation": "NRS § 338.010 et seq.", "last_verified": "2026-01-01"},
    "NH": {"state": "New Hampshire", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "RSA 228:61 (highway only)", "last_verified": "2026-01-01"},
    "NJ": {"state": "New Jersey", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "New Jersey Department of Labor and Workforce Development", "threshold_public_works_usd": 2000, "davis_bacon_applies": True, "citation": "N.J.S.A. 34:11-56.25 et seq.", "last_verified": "2026-01-01"},
    "NM": {"state": "New Mexico", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "New Mexico Department of Workforce Solutions", "threshold_public_works_usd": 60000, "davis_bacon_applies": True, "citation": "NMSA § 13-4-10 et seq.", "last_verified": "2026-01-01"},
    "NY": {"state": "New York", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "New York Department of Labor", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "Labor Law § 220 et seq.", "last_verified": "2026-01-01"},
    "NC": {"state": "North Carolina", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "N.C. Gen. Stat. § 133-10 (repealed)", "last_verified": "2026-01-01"},
    "ND": {"state": "North Dakota", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "N.D. Cent. Code § 34-14-01 (no current general PW law)", "last_verified": "2026-01-01"},
    "OH": {"state": "Ohio", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Ohio Department of Commerce - Wage and Hour Bureau", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "ORC § 4115.03 et seq.", "last_verified": "2026-01-01"},
    "OK": {"state": "Oklahoma", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "40 O.S. § 196.1 (no current general PW law)", "last_verified": "2026-01-01"},
    "OR": {"state": "Oregon", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Oregon Bureau of Labor and Industries (BOLI)", "threshold_public_works_usd": 50000, "davis_bacon_applies": True, "citation": "ORS § 279C.800 et seq.", "last_verified": "2026-01-01"},
    "PA": {"state": "Pennsylvania", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Pennsylvania Department of Labor and Industry", "threshold_public_works_usd": 25000, "davis_bacon_applies": True, "citation": "43 P.S. § 165-1 et seq.", "last_verified": "2026-01-01"},
    "RI": {"state": "Rhode Island", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Rhode Island Department of Labor and Training", "threshold_public_works_usd": 1000, "davis_bacon_applies": True, "citation": "R.I. Gen. Laws § 37-13-1 et seq.", "last_verified": "2026-01-01"},
    "SC": {"state": "South Carolina", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "S.C. Code Ann. § 6-5-10 (no current general PW law)", "last_verified": "2026-01-01"},
    "SD": {"state": "South Dakota", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "SDCL § 5-18A-8 (no current general PW law)", "last_verified": "2026-01-01"},
    "TN": {"state": "Tennessee", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "TCA § 66-34-301 (no current general PW law)", "last_verified": "2026-01-01"},
    "TX": {"state": "Texas", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Tex. Gov't Code § 2258.001 et seq.", "last_verified": "2026-01-01"},
    "UT": {"state": "Utah", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Utah Code § 34-5-1 (highway projects only)", "last_verified": "2026-01-01"},
    "VT": {"state": "Vermont", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "21 V.S.A. § 391 (highway projects only)", "last_verified": "2026-01-01"},
    "VA": {"state": "Virginia", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Virginia Department of Labor and Industry", "threshold_public_works_usd": 500000, "davis_bacon_applies": True, "citation": "Code of Va. § 2.2-4321.3", "last_verified": "2026-01-01"},
    "WA": {"state": "Washington", "prevailing_wage_law": True, "law_scope": "State public construction contracts", "administered_by": "Washington Department of Labor and Industries (L&I)", "threshold_public_works_usd": 0, "davis_bacon_applies": True, "citation": "RCW § 39.12.010 et seq.", "last_verified": "2026-01-01"},
    "WV": {"state": "West Virginia", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "W. Va. Code § 21-5A-1 (repealed 2016)", "last_verified": "2026-01-01"},
    "WI": {"state": "Wisconsin", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Wis. Stat. § 66.0903 (repealed 2017-18)", "last_verified": "2026-01-01"},
    "WY": {"state": "Wyoming", "prevailing_wage_law": False, "law_scope": "No general prevailing wage law; federal Davis-Bacon applies to federally funded projects", "administered_by": "N/A", "threshold_public_works_usd": None, "davis_bacon_applies": True, "citation": "Wyo. Stat. § 27-4-501 (no current general PW law)", "last_verified": "2026-01-01"},
}

CONTRACTOR_LICENSING: dict[str, dict] = {
    "AL": {"state": "Alabama", "state_license_required": True, "authority": "Alabama Licensing Board for General Contractors", "authority_url": "https://www.genconbd.alabama.gov", "threshold_usd": 10000, "license_classes": ["Class A - General", "Class B - Sub/Specialty"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "AK": {"state": "Alaska", "state_license_required": False, "authority": "Municipal/Local Jurisdictions", "authority_url": "https://www.commerce.alaska.gov", "threshold_usd": 0, "license_classes": [], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "AZ": {"state": "Arizona", "state_license_required": True, "authority": "Arizona Registrar of Contractors (ROC)", "authority_url": "https://roc.az.gov", "threshold_usd": 1000, "license_classes": ["Class A - General Engineering", "Class B - General Building", "Class C - Specialty (over 50 categories)", "Class CR - Residential"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "AR": {"state": "Arkansas", "state_license_required": True, "authority": "Arkansas Contractors Licensing Board", "authority_url": "https://www.aclb.arkansas.gov", "threshold_usd": 20000, "license_classes": ["Class A - General", "Class B - Sub/Specialty"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "CA": {"state": "California", "state_license_required": True, "authority": "California Contractors State License Board (CSLB)", "authority_url": "https://www.cslb.ca.gov", "threshold_usd": 500, "license_classes": ["Class A - General Engineering", "Class B - General Building", "Class C - Specialty (over 40 categories)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "CO": {"state": "Colorado", "state_license_required": False, "authority": "DORA (specific trades) / Local Jurisdictions (GC)", "authority_url": "https://dora.colorado.gov", "threshold_usd": 0, "license_classes": [], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "CT": {"state": "Connecticut", "state_license_required": True, "authority": "Connecticut Department of Consumer Protection", "authority_url": "https://portal.ct.gov/DCP", "threshold_usd": 200, "license_classes": ["Home Improvement Contractor (HIC)", "New Home Construction Contractor", "Tradesperson licenses (Electrical, Plumbing, HVAC)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "DE": {"state": "Delaware", "state_license_required": True, "authority": "Delaware Division of Revenue / Local Jurisdictions", "authority_url": "https://revenue.delaware.gov", "threshold_usd": 0, "license_classes": ["Home Improvement Contractor", "Trade licenses (Electrical, Plumbing, HVAC)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "DC": {"state": "District of Columbia", "state_license_required": True, "authority": "District of Columbia Department of Licensing and Consumer Protection (DLCP)", "authority_url": "https://dlcp.dc.gov", "threshold_usd": 0, "license_classes": ["General Contractor (Basic Business License)", "Home Improvement Contractor"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "FL": {"state": "Florida", "state_license_required": True, "authority": "Florida Construction Industry Licensing Board (CILB)", "authority_url": "https://www.myfloridalicense.com/DBPR/construction-industry-licensing", "threshold_usd": 1, "license_classes": ["Certified General Contractor", "Certified Building Contractor", "Certified Residential Contractor", "Registered Contractor (local jurisdiction)"], "renewal_years": 2, "ce_hours_required": 14, "last_verified": "2026-01-01"},
    "GA": {"state": "Georgia", "state_license_required": True, "authority": "Georgia State Licensing Board for Residential and General Contractors", "authority_url": "https://sos.ga.gov/index.php/licensing/plb/45", "threshold_usd": 2500, "license_classes": ["Class I - Residential/Light Commercial", "Class II - General Contractor"], "renewal_years": 2, "ce_hours_required": 6, "last_verified": "2026-01-01"},
    "HI": {"state": "Hawaii", "state_license_required": True, "authority": "Hawaii Department of Commerce and Consumer Affairs (DCCA) - Professional and Vocational Licensing", "authority_url": "https://cca.hawaii.gov/pvl", "threshold_usd": 1000, "license_classes": ["A - General Engineering", "B - General Building", "C - Specialty (over 25 categories)", "D - Specialty"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "ID": {"state": "Idaho", "state_license_required": False, "authority": "Idaho Department of Labor (Public Works) / Division of Building Safety (trades)", "authority_url": "https://dbs.idaho.gov", "threshold_usd": 0, "license_classes": ["Public Works Contractor", "Electrical, Plumbing, HVAC (specialty trades only)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "IL": {"state": "Illinois", "state_license_required": False, "authority": "Illinois Department of Financial and Professional Regulation (IDFPR)", "authority_url": "https://idfpr.illinois.gov", "threshold_usd": 0, "license_classes": ["Roofing Contractor (only statewide construction license)", "Trade licenses: Electrical, Plumbing"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "IN": {"state": "Indiana", "state_license_required": True, "authority": "Indiana Professional Licensing Agency (PLA) / Office of the Indiana Attorney General (HIC)", "authority_url": "https://www.in.gov/pla", "threshold_usd": 0, "license_classes": ["Residential Contractor (Home Improvement)", "Trade licenses: Plumbing, Electrical (via certifications)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "IA": {"state": "Iowa", "state_license_required": False, "authority": "Local Jurisdictions / Iowa Utilities Board (specialty trades)", "authority_url": "https://iub.iowa.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing, Mechanical (specialty only)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "KS": {"state": "Kansas", "state_license_required": False, "authority": "Local Jurisdictions / Kansas State Board of Technical Professions (specialty)", "authority_url": "https://www.ksbtp.ks.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing, HVAC (specialty only)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "KY": {"state": "Kentucky", "state_license_required": True, "authority": "Kentucky Department of Housing, Buildings and Construction", "authority_url": "https://dhbc.ky.gov", "threshold_usd": 10000, "license_classes": ["Class A - General (>$100,000)", "Class B - Building ($10,000-$100,000)", "Class C - Residential"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "LA": {"state": "Louisiana", "state_license_required": True, "authority": "Louisiana State Licensing Board for Contractors", "authority_url": "https://www.lslbc.louisiana.gov", "threshold_usd": 50000, "license_classes": ["Class A - General Commercial (>$50,000)", "Class B - Commercial ($10,000-$50,000)", "Class C - Residential", "Specialty Subcontractor"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "ME": {"state": "Maine", "state_license_required": True, "authority": "Maine Department of Professional and Financial Regulation - Contractors' Registration Program", "authority_url": "https://www.maine.gov/pfr/professionallicensing", "threshold_usd": 3000, "license_classes": ["Residential Contractor (Home Improvement)", "Lead Renovation Contractor"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "MD": {"state": "Maryland", "state_license_required": True, "authority": "Maryland Home Improvement Commission (MHIC) / Maryland Home Builder Registration Unit", "authority_url": "https://www.mhic.state.md.us", "threshold_usd": 100, "license_classes": ["Home Improvement Contractor (MHIC)", "Home Builder (MHBR)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "MA": {"state": "Massachusetts", "state_license_required": True, "authority": "Massachusetts Office of Consumer Affairs and Business Regulation", "authority_url": "https://www.mass.gov/orgs/office-of-consumer-affairs-and-business-regulation", "threshold_usd": 1000, "license_classes": ["Construction Supervisor License (CSL)", "Home Improvement Contractor (HIC)"], "renewal_years": 2, "ce_hours_required": 12, "last_verified": "2026-01-01"},
    "MI": {"state": "Michigan", "state_license_required": True, "authority": "Michigan Department of Licensing and Regulatory Affairs (LARA) - Bureau of Construction Codes", "authority_url": "https://www.michigan.gov/lara/bureau-list/bcc", "threshold_usd": 600, "license_classes": ["Residential Builder", "Residential Maintenance and Alteration Contractor", "Electrical, Plumbing, Mechanical (specialty)"], "renewal_years": 3, "ce_hours_required": 3, "last_verified": "2026-01-01"},
    "MN": {"state": "Minnesota", "state_license_required": True, "authority": "Minnesota Department of Labor and Industry - Construction Codes and Licensing", "authority_url": "https://www.dli.mn.gov/business/residential-contractors-remodelers-roofers", "threshold_usd": 15000, "license_classes": ["Residential Building Contractor", "Residential Remodeler", "Manufactured Home Installer"], "renewal_years": 2, "ce_hours_required": 14, "last_verified": "2026-01-01"},
    "MS": {"state": "Mississippi", "state_license_required": True, "authority": "Mississippi State Board of Contractors", "authority_url": "https://www.msboc.us", "threshold_usd": 50000, "license_classes": ["Class A - General Building", "Class B - Building up to $1,500,000", "Class C - Specialty", "Class R - Residential"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "MO": {"state": "Missouri", "state_license_required": False, "authority": "Local Jurisdictions / Missouri Division of Professional Registration (specialty)", "authority_url": "https://pr.mo.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing (specialty only at state level)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "MT": {"state": "Montana", "state_license_required": True, "authority": "Montana Department of Labor and Industry - Building Codes Bureau", "authority_url": "https://bsd.dli.mt.gov/building-codes-permits/", "threshold_usd": 1, "license_classes": ["Construction Contractor Registration", "Electrical, Plumbing (specialty)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NE": {"state": "Nebraska", "state_license_required": False, "authority": "Local Jurisdictions / Nebraska Electrical Division and Plumbing Division (specialty)", "authority_url": "https://energy.nebraska.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing, HVAC (specialty only)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NV": {"state": "Nevada", "state_license_required": True, "authority": "Nevada State Contractors Board", "authority_url": "https://www.nvcontractorsboard.com", "threshold_usd": 1000, "license_classes": ["Class A - General Engineering", "Class B - General Building", "Class C - Specialty (over 40 categories)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NH": {"state": "New Hampshire", "state_license_required": False, "authority": "NH Office of Professional Licensure and Certification / NH Insurance Dept (HIC bond)", "authority_url": "https://www.oplc.nh.gov", "threshold_usd": 0, "license_classes": ["Home Improvement Contractor Registration", "Electrical, Plumbing (specialty)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NJ": {"state": "New Jersey", "state_license_required": True, "authority": "New Jersey Division of Consumer Affairs - Contractor's Registration Act", "authority_url": "https://www.njconsumeraffairs.gov/hic", "threshold_usd": 500, "license_classes": ["Home Improvement Contractor (HIC)", "New Home Builder Registration", "Electrical, Plumbing (specialty)"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NM": {"state": "New Mexico", "state_license_required": True, "authority": "New Mexico Construction Industries Division (CID)", "authority_url": "https://www.rld.nm.gov/construction-industries-and-manufactured-housing", "threshold_usd": 10000, "license_classes": ["General Contractor (GB-98)", "Residential (RB-98)", "Trade Specialty licenses"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NY": {"state": "New York", "state_license_required": False, "authority": "Local Jurisdictions (NYC DCA, Westchester, Nassau, Suffolk counties)", "authority_url": "https://www.nyc.gov/site/dca/businesses/licenses.page", "threshold_usd": 0, "license_classes": ["Home Improvement Contractor (NYC/Westchester/Nassau/Suffolk)", "Local licenses only"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "NC": {"state": "North Carolina", "state_license_required": True, "authority": "North Carolina Licensing Board for General Contractors", "authority_url": "https://www.nclbgc.org", "threshold_usd": 30000, "license_classes": ["Limited (under $500,000)", "Intermediate ($500,000-$1,000,000)", "Unlimited (over $1,000,000)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "ND": {"state": "North Dakota", "state_license_required": True, "authority": "North Dakota Secretary of State", "authority_url": "https://www.sos.nd.gov", "threshold_usd": 2000, "license_classes": ["Contractor Registration (Secretary of State)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "OH": {"state": "Ohio", "state_license_required": False, "authority": "Ohio Construction Industry Licensing Board (OCILB) / Local jurisdictions for GC", "authority_url": "https://com.ohio.gov/divisions-and-programs/industrial-compliance/board-and-councils/ohio-construction-industry-licensing-board", "threshold_usd": 0, "license_classes": ["Electrical (statewide)", "Plumbing (statewide)", "HVAC (statewide)", "Hydronics", "Refrigeration"], "renewal_years": 3, "ce_hours_required": 24, "last_verified": "2026-01-01"},
    "OK": {"state": "Oklahoma", "state_license_required": True, "authority": "Oklahoma Construction Industries Board", "authority_url": "https://www.ok.gov/cib", "threshold_usd": 2500, "license_classes": ["Class A - General", "Class B - Building", "Specialty Subcontractor"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "OR": {"state": "Oregon", "state_license_required": True, "authority": "Oregon Construction Contractors Board (CCB)", "authority_url": "https://www.oregon.gov/ccb", "threshold_usd": 1, "license_classes": ["Residential General Contractor", "Residential Specialty Contractor", "Commercial General Contractor", "Commercial Specialty Contractor", "Landscape Contractor"], "renewal_years": 2, "ce_hours_required": 16, "last_verified": "2026-01-01"},
    "PA": {"state": "Pennsylvania", "state_license_required": False, "authority": "Pennsylvania Office of Attorney General - Bureau of Consumer Protection", "authority_url": "https://www.attorneygeneral.gov/businesses-and-organizations/home-improvement-contractor-registration/", "threshold_usd": 5000, "license_classes": ["Home Improvement Contractor (HIC Registration)"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "RI": {"state": "Rhode Island", "state_license_required": True, "authority": "Rhode Island Department of Business Regulation - Contractors' Registration and Licensing Board", "authority_url": "https://dbr.ri.gov/contractors-and-building-design-fire-professionals-board-accountancy/contractors-registration-and", "threshold_usd": 1000, "license_classes": ["Class A - General Building", "Class B - Specialty", "Class C - Residential"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "SC": {"state": "South Carolina", "state_license_required": True, "authority": "South Carolina Contractors' Licensing Board (CLB)", "authority_url": "https://llr.sc.gov/clb", "threshold_usd": 5000, "license_classes": ["Class I - Unlimited", "Class II - up to $5,000,000", "Class III - up to $1,500,000", "Class IV - up to $500,000", "Class V - Residential"], "renewal_years": 2, "ce_hours_required": 8, "last_verified": "2026-01-01"},
    "SD": {"state": "South Dakota", "state_license_required": False, "authority": "Local Jurisdictions / South Dakota State Electrical Commission (specialty)", "authority_url": "https://dlr.sd.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing (specialty only)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "TN": {"state": "Tennessee", "state_license_required": True, "authority": "Tennessee Board for Licensing Contractors", "authority_url": "https://www.tn.gov/commerce/regboards/contractors.html", "threshold_usd": 25000, "license_classes": ["BC-A General Contractor", "BC-B Building Contractor", "BC-C Residential Contractor", "BC-D Masonry Contractor"], "renewal_years": 2, "ce_hours_required": 8, "last_verified": "2026-01-01"},
    "TX": {"state": "Texas", "state_license_required": False, "authority": "Texas Department of Licensing and Regulation (TDLR) - specific trades only", "authority_url": "https://www.tdlr.texas.gov", "threshold_usd": 0, "license_classes": ["HVAC Contractor", "Plumbing Contractor", "Electrical Contractor", "Residential Appliance Installer", "Other specialty trades via TDLR"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "UT": {"state": "Utah", "state_license_required": True, "authority": "Utah Division of Occupational and Professional Licensing (DOPL)", "authority_url": "https://dopl.utah.gov", "threshold_usd": 3000, "license_classes": ["Class A100 - General Engineering", "Class B100 - General Building", "Class C - Specialty (over 50 categories)", "Class E - Elevator", "Class R100 - Residential"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "VT": {"state": "Vermont", "state_license_required": False, "authority": "Vermont Office of Professional Regulation (specialty trades only)", "authority_url": "https://sos.vermont.gov/opr", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing, Fire Suppression (specialty only)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "VA": {"state": "Virginia", "state_license_required": True, "authority": "Virginia Department of Professional and Occupational Regulation (DPOR)", "authority_url": "https://www.dpor.virginia.gov", "threshold_usd": 1000, "license_classes": ["Class A - $120,000+ annually", "Class B - $10,000-$120,000 annually", "Class C - $1,000-$10,000 annually"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "WA": {"state": "Washington", "state_license_required": True, "authority": "Washington State Department of Labor and Industries (L&I)", "authority_url": "https://lni.wa.gov/licensing-permits/contractors", "threshold_usd": 1, "license_classes": ["General Contractor (General)", "Specialty Contractor"], "renewal_years": 2, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "WV": {"state": "West Virginia", "state_license_required": True, "authority": "West Virginia Contractors Licensing Board", "authority_url": "https://wvclb.wv.gov", "threshold_usd": 2500, "license_classes": ["Class A - Unlimited", "Class B - up to $2,500,000", "Class C - up to $500,000", "Class D - up to $100,000"], "renewal_years": 1, "ce_hours_required": 0, "last_verified": "2026-01-01"},
    "WI": {"state": "Wisconsin", "state_license_required": True, "authority": "Wisconsin Department of Safety and Professional Services (DSPS)", "authority_url": "https://dsps.wi.gov", "threshold_usd": 1, "license_classes": ["Dwelling Contractor Qualifier (DCQ)", "Dwelling Contractor Certification", "Trade licenses: Electrical, Plumbing, HVAC"], "renewal_years": 2, "ce_hours_required": 12, "last_verified": "2026-01-01"},
    "WY": {"state": "Wyoming", "state_license_required": False, "authority": "Local Jurisdictions / Wyoming Department of Fire Prevention and Electrical Safety (specialty)", "authority_url": "https://wsfm.wyo.gov", "threshold_usd": 0, "license_classes": ["Electrical, Plumbing (specialty only at state level)"], "renewal_years": 0, "ce_hours_required": 0, "last_verified": "2026-01-01"},
}

# Topics the cited datasets do not cover. Named explicitly so that a caller
# asking for one gets a straight answer instead of a confident invention.
UNCOVERED_TOPICS = {
    "retainage_limit": "No sourced dataset in this repository states statutory retainage limits. The only file that ever carried the field held three states and was marked as a demonstration.",
}
