"""
worden_university.py — server-side course registry and exam answer keys.

GENERATED by wordenuniversity/scripts/build-courses.mjs. Do not hand-edit:
change the course JSON under wordenuniversity/content/ and re-run that script.

The answer key lives HERE and is never serialised to a browser. The original
front end shipped the correct index alongside every question, so any crew
member who opened devtools could pass an OSHA exam without reading a word. A
certificate that can be self-awarded is not a compliance record — it is a
liability, because it says a worker is trained when they are not.
"""

from typing import Dict, List

PASS_MARK = 80          # percent required to certify
CERT_VALID_DAYS = 365   # annual recertification, matching OSHA practice

COURSES: Dict[str, dict] = {
    "paving": {
        "title": "Asphalt Paving Fundamentals",
        "subtitle": "The Worden Standard — Base, Mat & Compaction",
        "hours": "3.5",
        "module_ids": ["p1", "p2", "p3", "p4", "p5", "p6"],
        "question_count": 10,
        "answer_key": [2, 1, 2, 1, 0, 1, 2, 1, 1, 2],
    },
    "trafficcontrol": {
        "title": "Work Zone Traffic Control",
        "subtitle": "MUTCD Part 6 · Flagging · Setup",
        "hours": "2.5",
        "module_ids": ["t1", "t2", "t3", "t4", "t5"],
        "question_count": 10,
        "answer_key": [1, 1, 1, 1, 2, 1, 2, 1, 1, 2],
    },
    "dot": {
        "title": "DOT Compliance for Crew Drivers",
        "subtitle": "CDL · Medical Cards · Hours of Service",
        "hours": "2.5",
        "module_ids": ["d1", "d2", "d3", "d4", "d5"],
        "question_count": 10,
        "answer_key": [1, 1, 2, 2, 2, 1, 0, 1, 1, 0],
    },
    "equipment": {
        "title": "Equipment Safety & Operation",
        "subtitle": "Pavers · Rollers · Skid Steers · Loaders",
        "hours": "2.5",
        "module_ids": ["e1", "e2", "e3", "e4", "e5"],
        "question_count": 10,
        "answer_key": [1, 1, 1, 2, 1, 2, 1, 2, 1, 2],
    },
    "classification": {
        "title": "Worker Classification",
        "subtitle": "Employee vs. Contractor vs. Day Labor",
        "hours": "2.5",
        "module_ids": ["c1", "c2", "c3", "c4", "c5", "c6"],
        "question_count": 8,
        "answer_key": [2, 1, 2, 2, 2, 2, 1, 1],
    },
    "osha": {
        "title": "OSHA Construction Safety",
        "subtitle": "Compliance, Documentation, Prevention",
        "hours": "4",
        "module_ids": ["o1", "o2", "o3", "o4", "o5", "o6", "o7", "o8", "o9", "o10"],
        "question_count": 8,
        "answer_key": [0, 1, 3, 1, 2, 2, 2, 2],
    },
}


def answer_key(course_id: str) -> List[int]:
    c = COURSES.get(course_id)
    return list(c["answer_key"]) if c else []
