"""Add Starbase LMS models

Revision ID: 59a76ce309d5
Revises: q5r8s3t9u2v7
Create Date: 2026-07-11 17:57:58.077162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a76ce309d5'
down_revision: Union[str, Sequence[str], None] = 'q5r8s3t9u2v7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_courses_id'), 'lms_courses', ['id'], unique=False)
    op.create_index(op.f('ix_lms_courses_slug'), 'lms_courses', ['slug'], unique=True)
    op.create_index(op.f('ix_lms_courses_tenant_id'), 'lms_courses', ['tenant_id'], unique=False)
    op.create_table('lms_course_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_course_modules_course_id'), 'lms_course_modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_lms_course_modules_id'), 'lms_course_modules', ['id'], unique=False)
    op.create_table('lms_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['lms_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_email', name='uq_enrollment')
    )
    op.create_index(op.f('ix_lms_enrollments_course_id'), 'lms_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_lms_enrollments_id'), 'lms_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_lms_enrollments_user_email'), 'lms_enrollments', ['user_email'], unique=False)
    op.create_table('lms_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=True),
    sa.Column('quiz_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['lms_course_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lms_lessons_id'), 'lms_lessons', ['id'], unique=False)
    op.create_index(op.f('ix_lms_lessons_module_id'), 'lms_lessons', ['module_id'], unique=False)
    op.create_table('lms_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['lms_enrollments.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lms_lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'lesson_id', name='uq_progress')
    )
    op.create_index(op.f('ix_lms_progress_enrollment_id'), 'lms_progress', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_lms_progress_id'), 'lms_progress', ['id'], unique=False)
    op.create_index(op.f('ix_lms_progress_lesson_id'), 'lms_progress', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lms_progress_lesson_id'), table_name='lms_progress')
    op.drop_index(op.f('ix_lms_progress_id'), table_name='lms_progress')
    op.drop_index(op.f('ix_lms_progress_enrollment_id'), table_name='lms_progress')
    op.drop_table('lms_progress')
    op.drop_index(op.f('ix_lms_lessons_module_id'), table_name='lms_lessons')
    op.drop_index(op.f('ix_lms_lessons_id'), table_name='lms_lessons')
    op.drop_table('lms_lessons')
    op.drop_index(op.f('ix_lms_enrollments_user_email'), table_name='lms_enrollments')
    op.drop_index(op.f('ix_lms_enrollments_id'), table_name='lms_enrollments')
    op.drop_index(op.f('ix_lms_enrollments_course_id'), table_name='lms_enrollments')
    op.drop_table('lms_enrollments')
    op.drop_index(op.f('ix_lms_course_modules_id'), table_name='lms_course_modules')
    op.drop_index(op.f('ix_lms_course_modules_course_id'), table_name='lms_course_modules')
    op.drop_table('lms_course_modules')
    op.drop_index(op.f('ix_lms_courses_tenant_id'), table_name='lms_courses')
    op.drop_index(op.f('ix_lms_courses_slug'), table_name='lms_courses')
    op.drop_index(op.f('ix_lms_courses_id'), table_name='lms_courses')
    op.drop_table('lms_courses')
    # ### end Alembic commands ###
