"""Add Estimate portal fields

Revision ID: 6b100440d78b
Revises: 59a76ce309d5
Create Date: 2026-07-11 18:06:10.015937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b100440d78b'
down_revision: Union[str, Sequence[str], None] = '59a76ce309d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('public_token', sa.String(length=100), nullable=True))
    op.add_column('estimates', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('estimates', sa.Column('deposit_amount', sa.Float(), nullable=True))
    op.add_column('estimates', sa.Column('signature_data_url', sa.Text(), nullable=True))
    op.add_column('estimates', sa.Column('signed_at_utc', sa.DateTime(timezone=True), nullable=True))
    op.add_column('estimates', sa.Column('terms_accepted', sa.Boolean(), nullable=True))
    op.add_column('estimates', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('estimates', sa.Column('payment_status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_estimates_public_token'), 'estimates', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estimates_public_token'), table_name='estimates')
    op.drop_column('estimates', 'payment_status')
    op.drop_column('estimates', 'payment_method')
    op.drop_column('estimates', 'terms_accepted')
    op.drop_column('estimates', 'signed_at_utc')
    op.drop_column('estimates', 'signature_data_url')
    op.drop_column('estimates', 'deposit_amount')
    op.drop_column('estimates', 'total_amount')
    op.drop_column('estimates', 'public_token')
    # ### end Alembic commands ###
