"""Add Mapbox geo fields to Job

Revision ID: 971900dc0bd5
Revises: 6b100440d78b
Create Date: 2026-07-11 18:15:46.871333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971900dc0bd5'
down_revision: Union[str, Sequence[str], None] = '6b100440d78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('geo_lat', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('geo_lng', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('scope_geojson', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('pictures_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'pictures_json')
    op.drop_column('jobs', 'scope_geojson')
    op.drop_column('jobs', 'geo_lng')
    op.drop_column('jobs', 'geo_lat')
    # ### end Alembic commands ###
