"""Complete the chain: the 7 tables and 3 columns only create_all() could build.

Building a database from this migration chain alone used to leave out
daily_checkins, inbox_messages, market_sites, staff_users, worker_documents,
worker_profiles and users, plus tenants.subscription_tier / stripe_customer_id /
stripe_subscription_id. Production has them anyway because AUTO_CREATE_TABLES
runs create_all() at boot — which made that setting silently load-bearing: the
first rebuild-from-scratch without it would have produced a schema the app
cannot run on (auth alone needs users and tenants.subscription_tier).

The overnight repo audit found this gap already expressed as a migration in the
jworden-luxury-paving fork (r6s9t4u0v3w8). That file branches from a parallel
chain and cannot be applied here, so this is its content re-expressed in THIS
chain — generated by alembic autogenerate against a chain-built database, then
pruned to exactly the missing tables/columns.

Every operation is guarded by an inspector check, because production and any
create_all()'d environment already have all of it: there this migration is a
clean no-op, and only a genuinely chain-built database gets the new objects.

Deliberately NOT included from the autogenerate diff, and why:
  - index renames on 10 existing tables (ix_aue_* -> ix_ad_url_exclusions_*
    and similar): pure naming churn between migration-era short names and
    model-derived names; rebuilding indexes on live tables buys nothing.
  - unique-constraint vs unique-index flips (estimates, jobs, work_orders,
    lms_certifications, vdot_bids): schema-equivalent enforcement either way.
  - site_evaluations columns tightened to NOT NULL: real model/DB drift, but
    tightening nullability against live rows is its own change with its own
    failure mode, not part of completing the chain.

Revision ID: z6c7h8a9i0n1
Revises: y4s1t2a3t4u5
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'z6c7h8a9i0n1'
down_revision: Union[str, Sequence[str], None] = 'y4s1t2a3t4u5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _insp():
    return sa.inspect(op.get_bind())


def _has_table(name: str) -> bool:
    return name in _insp().get_table_names()


def _cols(table: str) -> set:
    return {c["name"] for c in _insp().get_columns(table)}


def upgrade() -> None:
    if not _has_table('daily_checkins'):
        op.create_table('daily_checkins',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('photo_filename', sa.String(length=300), nullable=True),
            sa.Column('gps_lat', sa.Float(), nullable=True),
            sa.Column('gps_lng', sa.Float(), nullable=True),
            sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_daily_checkins_id'), 'daily_checkins', ['id'], unique=False)
        op.create_index(op.f('ix_daily_checkins_user_id'), 'daily_checkins', ['user_id'], unique=False)

    if not _has_table('inbox_messages'):
        op.create_table('inbox_messages',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('email_account', sa.String(length=254), nullable=False),
            sa.Column('sender_name', sa.String(length=120), nullable=True),
            sa.Column('sender_email', sa.String(length=254), nullable=False),
            sa.Column('subject', sa.String(length=500), nullable=True),
            sa.Column('body_summary', sa.Text(), nullable=True),
            sa.Column('category', sa.String(length=60), nullable=False),
            sa.Column('importance_score', sa.Integer(), nullable=False),
            sa.Column('is_lead', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_inbox_messages_email_account'), 'inbox_messages', ['email_account'], unique=False)
        op.create_index(op.f('ix_inbox_messages_id'), 'inbox_messages', ['id'], unique=False)

    if not _has_table('market_sites'):
        op.create_table('market_sites',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.String(length=60), nullable=False),
            sa.Column('hostname', sa.String(length=200), nullable=False),
            sa.Column('route_mode', sa.String(length=50), nullable=False),
            sa.Column('site_title', sa.String(length=200), nullable=True),
            sa.Column('site_description', sa.Text(), nullable=True),
            sa.Column('primary_color', sa.String(length=20), nullable=True),
            sa.Column('accent_color', sa.String(length=20), nullable=True),
            sa.Column('hero_headline', sa.String(length=300), nullable=True),
            sa.Column('hero_subheadline', sa.Text(), nullable=True),
            sa.Column('local_weather_copy', sa.Text(), nullable=True),
            sa.Column('city_target', sa.String(length=100), nullable=True),
            sa.Column('state_target', sa.String(length=2), nullable=True),
            sa.Column('phone_override', sa.String(length=30), nullable=True),
            sa.Column('is_active', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('hostname', name='uq_market_sites_hostname'),
        )
        op.create_index(op.f('ix_market_sites_hostname'), 'market_sites', ['hostname'], unique=False)
        op.create_index(op.f('ix_market_sites_id'), 'market_sites', ['id'], unique=False)
        op.create_index(op.f('ix_market_sites_tenant_id'), 'market_sites', ['tenant_id'], unique=False)

    if not _has_table('staff_users'):
        op.create_table('staff_users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=60), nullable=False),
            sa.Column('role', sa.String(length=20), nullable=False),
            sa.Column('password_hash', sa.String(length=256), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username', name='uq_staff_username'),
        )
        op.create_index(op.f('ix_staff_users_id'), 'staff_users', ['id'], unique=False)
        op.create_index(op.f('ix_staff_users_username'), 'staff_users', ['username'], unique=True)

    if not _has_table('worker_documents'):
        op.create_table('worker_documents',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('profile_id', sa.Integer(), nullable=False),
            sa.Column('doc_type', sa.String(length=60), nullable=False),
            sa.Column('filename', sa.String(length=300), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('notes', sa.String(length=500), nullable=True),
            sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('reviewed_by', sa.String(length=60), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index(op.f('ix_worker_documents_doc_type'), 'worker_documents', ['doc_type'], unique=False)
        op.create_index(op.f('ix_worker_documents_id'), 'worker_documents', ['id'], unique=False)
        op.create_index(op.f('ix_worker_documents_profile_id'), 'worker_documents', ['profile_id'], unique=False)

    if not _has_table('worker_profiles'):
        op.create_table('worker_profiles',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('staff_user_id', sa.Integer(), nullable=True),
            sa.Column('full_name', sa.String(length=200), nullable=False),
            sa.Column('worker_type', sa.String(length=30), nullable=False),
            sa.Column('pay_type', sa.String(length=10), nullable=False),
            sa.Column('status', sa.String(length=20), nullable=False),
            sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('termination_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('phone', sa.String(length=30), nullable=True),
            sa.Column('email', sa.String(length=254), nullable=True),
            sa.Column('address', sa.String(length=400), nullable=True),
            sa.Column('ssn_last4', sa.String(length=4), nullable=True),
            sa.Column('cdl_number', sa.String(length=30), nullable=True),
            sa.Column('cdl_state', sa.String(length=2), nullable=True),
            sa.Column('cdl_class', sa.String(length=5), nullable=True),
            sa.Column('cdl_expiry', sa.DateTime(timezone=True), nullable=True),
            sa.Column('dot_medical_expiry', sa.DateTime(timezone=True), nullable=True),
            sa.Column('fmcsa_clearinghouse_queried', sa.Boolean(), nullable=False),
            sa.Column('company_name', sa.String(length=200), nullable=True),
            sa.Column('ein', sa.String(length=20), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('staff_user_id', name='uq_worker_staff_user'),
        )
        op.create_index(op.f('ix_worker_profiles_id'), 'worker_profiles', ['id'], unique=False)
        op.create_index(op.f('ix_worker_profiles_staff_user_id'), 'worker_profiles', ['staff_user_id'], unique=False)

    if not _has_table('users'):
        # The FK targets tenants.tenant_id, which Postgres only accepts if that
        # column carries a unique constraint. create_all() satisfies this via
        # the model, but a chain-built tenants table may have only a plain
        # index — so ensure uniqueness first rather than let the FK fail.
        uniques = {u['name'] for u in _insp().get_unique_constraints('tenants')}
        unique_idx = {i['name'] for i in _insp().get_indexes('tenants') if i.get('unique')}
        if 'uq_tenants_tenant_id' not in uniques and not any(
            i.get('unique') and i['column_names'] == ['tenant_id']
            for i in _insp().get_indexes('tenants')
        ):
            op.create_unique_constraint('uq_tenants_tenant_id', 'tenants', ['tenant_id'])
        op.create_table('users',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.String(length=60), nullable=False),
            sa.Column('email', sa.String(length=254), nullable=False),
            sa.Column('hashed_password', sa.String(length=200), nullable=False),
            sa.Column('full_name', sa.String(length=150), nullable=True),
            sa.Column('role', sa.String(length=30), nullable=False),
            sa.Column('is_active', sa.Integer(), nullable=False),
            sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id']),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('email', name='uq_users_email'),
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
        op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)

    # ── tenants columns ───────────────────────────────────────────────────────
    tenant_cols = _cols('tenants')

    if 'subscription_tier' not in tenant_cols:
        # NOT NULL with existing rows: add with a server default and backfill,
        # the same dance y4s1t2a3t4u5 did for subscription_status. 'lite'
        # matches the model default; register_tenant always sets it explicitly.
        op.add_column('tenants', sa.Column(
            'subscription_tier', sa.String(length=30),
            nullable=True, server_default='lite',
        ))
        op.execute("UPDATE tenants SET subscription_tier = 'lite' WHERE subscription_tier IS NULL")
        op.alter_column('tenants', 'subscription_tier', nullable=False)

    if 'stripe_customer_id' not in tenant_cols:
        op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        op.create_index(op.f('ix_tenants_stripe_customer_id'), 'tenants', ['stripe_customer_id'], unique=False)

    if 'stripe_subscription_id' not in tenant_cols:
        op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        op.create_index(op.f('ix_tenants_stripe_subscription_id'), 'tenants', ['stripe_subscription_id'], unique=False)

    # ── blog_posts -> market_sites FK ─────────────────────────────────────────
    # x3d1r2i3f4t5 added blog_posts.market_site_id but could only create the FK
    # where market_sites already existed. Now it always does, so close the loop —
    # same name that migration used, skipped wherever any FK already covers it.
    if _has_table('blog_posts') and 'market_site_id' in _cols('blog_posts'):
        fks = _insp().get_foreign_keys('blog_posts')
        if not any(fk.get('constrained_columns') == ['market_site_id'] for fk in fks):
            op.create_foreign_key(
                'fk_blog_posts_market_site_id', 'blog_posts', 'market_sites',
                ['market_site_id'], ['id'],
            )


def downgrade() -> None:
    # Guarded like upgrade, so a partial apply can still be reversed. Only the
    # objects this migration could have created are touched.
    insp = _insp()

    if _has_table('blog_posts'):
        fks = {fk.get('name') for fk in insp.get_foreign_keys('blog_posts')}
        if 'fk_blog_posts_market_site_id' in fks:
            op.drop_constraint('fk_blog_posts_market_site_id', 'blog_posts', type_='foreignkey')

    tenant_cols = _cols('tenants')
    for col, idx in (
        ('stripe_subscription_id', 'ix_tenants_stripe_subscription_id'),
        ('stripe_customer_id', 'ix_tenants_stripe_customer_id'),
    ):
        if col in tenant_cols:
            if idx in {i['name'] for i in _insp().get_indexes('tenants')}:
                op.drop_index(op.f(idx), table_name='tenants')
            op.drop_column('tenants', col)
    if 'subscription_tier' in tenant_cols:
        op.drop_column('tenants', 'subscription_tier')

    for table in ('users', 'worker_profiles', 'worker_documents', 'staff_users',
                  'market_sites', 'inbox_messages', 'daily_checkins'):
        if _has_table(table):
            op.drop_table(table)

    uniques = {u['name'] for u in _insp().get_unique_constraints('tenants')}
    if 'uq_tenants_tenant_id' in uniques:
        op.drop_constraint('uq_tenants_tenant_id', 'tenants', type_='unique')
